name = "beer-bot-worker"
main = "src/index.ts"
compatibility_date = "2024-11-23"

# 環境変数はwrangler secretコマンドで設定してください
# wrangler secret put LINE_CHANNEL_ACCESS_TOKEN
# wrangler secret put LINE_CHANNEL_SECRET

[env.production]
name = "beer-bot-worker"

[env.preview]
name = "beer-bot-worker-preview"

